Integration jacoco
EnKarin/BookCrossingServer pull request #29
Opened 2022-07-04 14:04 UTC by EnKarin

2022-07-04 14:14 UTC, mfvanek requested changes

2022-07-04 14:14 UTC, mfvanek commented on pom.xml
> +                <version>2.22.2</version>
This version is default version inherited from Spring. You have not to specify it explicitly again.
Take a look at plugin management with Maven https://www.baeldung.com/maven-plugin-management

2022-07-04 16:05 UTC, EnKarin commented on pom.xml
> +                <version>2.22.2</version>
I missed it

2022-07-06 07:20 UTC, mfvanek approved these changes

2022-07-06 07:23 UTC, merged